@api=http://localhost:3000/todo/api

###
GET {{api}}/get-all HTTP/1.1

###
POST {{api}}/add HTTP/1.1
Content-Type: application/json

{
  "message": "Buy Milk"
}

###
POST {{api}}/update HTTP/1.1
Content-Type: application/json

{
  "id": "4b105ed7-bab6-459a-9fed-82bd67ca385d",
  "completed": true
}

###
PUT {{api}}/set-all HTTP/1.1
Content-Type: application/json

{
  "items": []
}